// Set current year in footer
document.getElementById("y").textContent = new Date().getFullYear();

// Google Scholar Live Citation Updater
class ScholarUpdater {
  constructor() {
    this.dataPath = "data/scholar.json";
    this.fallbackData = {
      totalCitations: 98,
      hIndex: 3,
      i10Index: 2,
      publications: [
        {
          id: "paper1",
          citations: 72,
        },
        {
          id: "paper2",
          citations: 21,
        },
        {
          id: "paper3",
          citations: 5,
        },
      ],
    };
  }

  async fetchScholarData() {
    try {
      this.showLoadingState();

      // Attempt to fetch from the local static JSON generated by GitHub Actions
      const response = await fetch(this.dataPath, { cache: "no-store" });

      if (!response.ok) {
        throw new Error("Network response was not ok, falling back.");
      }

      const rawData = await response.json();
      
      // Map the scraper's dictionary format to the UI's expected format
      const data = {
        totalCitations: rawData.total_citations,
        hIndex: rawData.h_index,
        i10Index: rawData.i10_index,
        publications: Object.keys(rawData.papers || {}).map(key => ({
          id: key,
          citations: rawData.papers[key]
        })),
        lastUpdated: new Date().toISOString() // Or get it from file metadata if needed
      };

      this.updateUI(data);
      this.hideLoadingState();

      // Cache the data
      localStorage.setItem("scholarData", JSON.stringify(data));
      localStorage.setItem("scholarLastUpdate", Date.now().toString());
    } catch (error) {
      console.warn(
        "Failed to fetch live data, using cached or fallback data:",
        error
      );
      this.handleFallback();
    }
  }

  handleFallback() {
    // Try to use cached data first
    const cachedData = localStorage.getItem("scholarData");
    const lastUpdate = localStorage.getItem("scholarLastUpdate");

    // Use cached data if it's less than 24 hours old
    if (cachedData && lastUpdate) {
      const hoursSinceUpdate =
        (Date.now() - parseInt(lastUpdate)) / (1000 * 60 * 60);
      if (hoursSinceUpdate < 24) {
        this.updateUI(JSON.parse(cachedData));
        this.hideLoadingState();
        return;
      }
    }

    // Fallback to hardcoded HTML data
    this.updateUI(this.fallbackData);
    this.hideLoadingState();
  }

  updateUI(data) {
    // Update citation count
    const citationElements = document.querySelectorAll(
      '[data-scholar="citations"]'
    );
    citationElements.forEach((el) => {
      el.textContent = data.totalCitations;
      el.classList.add("scholar-updated");
    });

    // Update h-index
    const hIndexElements = document.querySelectorAll(
      '[data-scholar="h-index"]'
    );
    hIndexElements.forEach((el) => {
      el.textContent = data.hIndex;
      el.classList.add("scholar-updated");
    });

    // Update i10-index
    const i10IndexElements = document.querySelectorAll(
      '[data-scholar="i10-index"]'
    );
    i10IndexElements.forEach((el) => {
      el.textContent = data.i10Index;
      el.classList.add("scholar-updated");
    });

    // Update individual paper citations
    if (data.publications && data.publications.length > 0) {
      data.publications.forEach((paper) => {
        const paperElements = document.querySelectorAll(
          `[data-paper-citations="${paper.id}"]`
        );
        paperElements.forEach((el) => {
          if (el.textContent !== paper.citations.toString()) {
            el.textContent = paper.citations;
            el.classList.add("scholar-updated");

            // Add a subtle notification for updated papers
            this.showPaperUpdateNotification(paper);
          }
        });
      });
    }

    // Add last updated timestamp
    this.addUpdateTimestamp(data.lastUpdated);
  }

  showPaperUpdateNotification(paper) {
    // Create a temporary notification for paper updates
    const notification = document.createElement("div");
    notification.style.cssText = `
      position: fixed;
      top: 20px;
      right: 20px;
      background: var(--card);
      border: 1px solid var(--line);
      border-radius: 8px;
      padding: 12px 16px;
      color: var(--fg);
      font-size: 0.9em;
      z-index: 1000;
      opacity: 0;
      transform: translateX(100%);
      transition: all 0.3s ease;
    `;

    notification.textContent = `Updated: ${paper.title.substring(0, 40)}... (${
      paper.citations
    } citations)`;

    document.body.appendChild(notification);

    // Animate in
    setTimeout(() => {
      notification.style.opacity = "1";
      notification.style.transform = "translateX(0)";
    }, 100);

    // Remove after 3 seconds
    setTimeout(() => {
      notification.style.opacity = "0";
      notification.style.transform = "translateX(100%)";
      setTimeout(() => {
        if (notification.parentNode) {
          notification.parentNode.removeChild(notification);
        }
      }, 300);
    }, 3000);
  }

  addUpdateTimestamp(timestamp) {
    const impactElement = document.querySelector(".scholar-impact");
    if (impactElement && timestamp) {
      const date = new Date(timestamp);
      const timeString = date.toLocaleString();

      let timestampEl = impactElement.querySelector(".last-updated");
      if (!timestampEl) {
        timestampEl = document.createElement("small");
        timestampEl.className = "last-updated";
        timestampEl.style.cssText =
          "display: block; margin-top: 8px; color: var(--muted); font-size: 0.85em;";
        impactElement.appendChild(timestampEl);
      }

      timestampEl.textContent = `Last updated: ${timeString}`;
    }
  }

  showLoadingState() {
    const loadingElements = document.querySelectorAll(
      "[data-scholar], [data-paper-citations]"
    );
    loadingElements.forEach((el) => {
      el.classList.add("scholar-loading");
    });
  }

  hideLoadingState() {
    const loadingElements = document.querySelectorAll(
      "[data-scholar], [data-paper-citations]"
    );
    loadingElements.forEach((el) => {
      el.classList.remove("scholar-loading");
    });
  }

  // Check for updates every hour when page is active
  startAutoUpdate() {
    setInterval(() => {
      if (!document.hidden) {
        this.fetchScholarData();
      }
    }, 3600000); // 1 hour
  }
}

// Initialize Scholar Updater when DOM is loaded
document.addEventListener("DOMContentLoaded", () => {
  const scholarUpdater = new ScholarUpdater();

  // Fetch data immediately
  scholarUpdater.fetchScholarData();

  // Start auto-update
  scholarUpdater.startAutoUpdate();

  // Also update when page becomes visible (user returns to tab)
  document.addEventListener("visibilitychange", () => {
    if (!document.hidden) {
      scholarUpdater.fetchScholarData();
    }
  });
});

// Add smooth scroll for navigation
document.querySelectorAll('a[href^="#"]').forEach((anchor) => {
  anchor.addEventListener("click", function (e) {
    e.preventDefault();
    const target = document.querySelector(this.getAttribute("href"));
    if (target) {
      target.scrollIntoView({
        behavior: "smooth",
        block: "start",
      });
    }
  });
});

// Dynamic active nav link based on scroll position
(function setupActiveNavOnScroll() {
  const nav = document.querySelector("nav.top");
  if (!nav) return;

  const navLinks = Array.from(nav.querySelectorAll("a"));
  const sectionByHref = new Map();

  navLinks.forEach((link) => {
    const href = link.getAttribute("href");
    if (!href) return;
    // Treat "#" as intro
    const selector = href === "#" ? "#intro" : href;
    const section = document.querySelector(selector);
    if (section) sectionByHref.set(href, section);
  });

  function setActiveLinkFor(selector) {
    navLinks.forEach((l) => l.classList.remove("active"));
    const match =
      nav.querySelector(`a[href="${selector}"]`) ||
      nav.querySelector('a[href="#"]');
    if (match) match.classList.add("active");
  }

  // Observe sections' visibility
  const observer = new IntersectionObserver(
    (entries) => {
      // Find the entry most in view near the top
      const visible = entries
        .filter((e) => e.isIntersecting)
        .sort(
          (a, b) =>
            Math.abs(a.boundingClientRect.top) -
            Math.abs(b.boundingClientRect.top)
        );
      if (visible.length) {
        const id = `#${visible[0].target.id}`;
        // Map back to original hrefs (handle intro vs #)
        const selector = id === "#intro" ? "#" : id;
        setActiveLinkFor(selector);
      }
    },
    {
      root: null,
      // Trigger when section enters the upper half of viewport
      rootMargin: "-40% 0px -60% 0px",
      threshold: [0, 0.25, 0.5, 0.75, 1],
    }
  );

  // Start observing
  sectionByHref.forEach((section) => observer.observe(section));

  // Update on hash change and on load
  window.addEventListener("hashchange", () => {
    const hash = window.location.hash || "#";
    setActiveLinkFor(hash);
  });

  // Initial set based on current scroll position
  setTimeout(() => {
    const hash = window.location.hash || "#";
    setActiveLinkFor(hash);
  }, 0);
})();

// --- Command Palette (⌘K) ---
class CommandPalette {
  constructor() {
    this.palette = document.getElementById("cmd-palette");
    this.input = document.getElementById("cmd-input");
    this.resultsContainer = document.getElementById("cmd-results");
    
    // Define the available commands
    this.commands = [
      { id: "projects", title: "Go to Projects", action: () => this.scrollTo("#projects"), icon: "🚀" },
      { id: "experience", title: "Go to Experience", action: () => this.scrollTo("#experience"), icon: "💼" },
      { id: "education", title: "Go to Education", action: () => this.scrollTo("#education"), icon: "🎓" },
      { id: "publications", title: "Go to Publications", action: () => this.scrollTo("#publications"), icon: "📚" },
      { id: "email", title: "Copy Email Address", action: () => this.copyText("deshpande.aditya16@gmail.com"), icon: "✉️" },
      { id: "github", title: "View GitHub", action: () => window.open("https://github.com/spacelord16", "_blank"), icon: "💻" },
      { id: "linkedin", title: "View LinkedIn", action: () => window.open("https://www.linkedin.com/in/adityadeshpande16/", "_blank"), icon: "🔗" },
      { id: "scholar", title: "View Google Scholar", action: () => window.open("https://scholar.google.com/citations?user=keOjVIEAAAAJ&hl=en", "_blank"), icon: "🎓" },
      { id: "theme", title: "Toggle Light/Dark Theme (Coming Soon)", action: () => alert("Stay in the dark side for now ;)"), icon: "🌓" }
    ];

    this.selectedIndex = 0;
    this.filteredCommands = [...this.commands];
    
    this.init();
  }

  init() {
    if (!this.palette || !this.input) return;

    // Listen for Cmd+K or Ctrl+K
    document.addEventListener("keydown", (e) => {
      if ((e.metaKey || e.ctrlKey) && e.key.toLowerCase() === "k") {
        e.preventDefault();
        this.toggle();
      }
      
      // Close on Escape
      if (e.key === "Escape" && !this.palette.classList.contains("cmd-hidden")) {
        this.close();
      }
    });

    // Close when clicking overlay
    this.palette.addEventListener("click", (e) => {
      if (e.target.classList.contains("cmd-overlay")) {
        this.close();
      }
    });

    // Handle typing
    this.input.addEventListener("input", (e) => {
      this.filterResults(e.target.value);
    });

    // Handle keyboard navigation
    this.input.addEventListener("keydown", (e) => {
      if (e.key === "ArrowDown") {
        e.preventDefault();
        this.selectedIndex = Math.min(this.selectedIndex + 1, this.filteredCommands.length - 1);
        this.renderResults();
      } else if (e.key === "ArrowUp") {
        e.preventDefault();
        this.selectedIndex = Math.max(this.selectedIndex - 1, 0);
        this.renderResults();
      } else if (e.key === "Enter") {
        e.preventDefault();
        if (this.filteredCommands[this.selectedIndex]) {
          this.executeCommand(this.filteredCommands[this.selectedIndex]);
        }
      }
    });
  }

  toggle() {
    if (this.palette.classList.contains("cmd-hidden")) {
      this.open();
    } else {
      this.close();
    }
  }

  open() {
    this.palette.classList.remove("cmd-hidden");
    this.input.value = "";
    this.filterResults("");
    this.input.focus();
    document.body.style.overflow = "hidden"; // Prevent background scrolling
  }

  close() {
    this.palette.classList.add("cmd-hidden");
    document.body.style.overflow = "";
    document.activeElement.blur();
  }

  filterResults(query) {
    const lowerQuery = query.toLowerCase();
    this.filteredCommands = this.commands.filter(c => 
      c.title.toLowerCase().includes(lowerQuery) || c.id.includes(lowerQuery)
    );
    this.selectedIndex = 0;
    this.renderResults();
  }

  renderResults() {
    this.resultsContainer.innerHTML = "";
    
    if (this.filteredCommands.length === 0) {
      const li = document.createElement("li");
      li.textContent = "No commands found...";
      li.style.color = "var(--muted)";
      li.style.pointerEvents = "none";
      this.resultsContainer.appendChild(li);
      return;
    }

    this.filteredCommands.forEach((cmd, index) => {
      const li = document.createElement("li");
      li.innerHTML = `<span>${cmd.icon}</span> <span>${cmd.title}</span>`;
      
      if (index === this.selectedIndex) {
        li.classList.add("cmd-selected");
        // Ensure scrolling follows selection
        li.scrollIntoView({ block: "nearest", behavior: "smooth" });
      }
      
      li.addEventListener("mouseenter", () => {
        this.selectedIndex = index;
        this.renderResults();
      });
      
      li.addEventListener("click", () => {
        this.executeCommand(cmd);
      });
      
      this.resultsContainer.appendChild(li);
    });
  }

  executeCommand(cmd) {
    this.close();
    cmd.action();
  }

  scrollTo(selector) {
    const target = document.querySelector(selector);
    if (target) {
      target.scrollIntoView({ behavior: "smooth", block: "start" });
    }
  }

  copyText(text) {
    navigator.clipboard.writeText(text).then(() => {
      const originalTitle = document.title;
      document.title = "Copied to clipboard!";
      setTimeout(() => document.title = originalTitle, 2000);
    }).catch(err => {
      console.warn("Clipboard access denied", err);
    });
  }
}

document.addEventListener("DOMContentLoaded", () => {
  new CommandPalette();
});

// --- Copy Email Function ---
function copyEmail(btn) {
  const email = "deshpande.aditya16@gmail.com";
  navigator.clipboard.writeText(email).then(() => {
    const originalContent = btn.innerHTML;
    btn.innerHTML = `Copied! <svg class="copy-icon" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"><polyline points="20 6 9 17 4 12"></polyline></svg>`;
    btn.classList.add("copied");
    
    setTimeout(() => {
      btn.innerHTML = originalContent;
      btn.classList.remove("copied");
    }, 2000);
  }).catch(err => {
    console.warn("Clipboard access denied", err);
  });
}
